---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: simplapp-sa
  namespace: dev
  
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: simpleapp-role
  namespace: dev
rules:
  - apiGroups: ["*"]
    resources: ["services", "pods", "endpoints"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: simpleapp-rolebinding
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: simpleapp-role
subjects:
  - kind: ServiceAccount
    name: simplapp-sa
    namespace: dev

---
apiVersion: v1
kind: Service
metadata:
  name: simpleapp
  namespace: dev
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    role: service
    app: simpleapp
  type: NodePort

---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    tags.dev.com/service: simpleapp
  name: simpleapp
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpleapp
      role: service
  template:
    metadata:
      name: simpleapp
      labels:
        app: simpleapp
        role: service
        tags.dev.com/service: simpleapp
        tags.dev.com/version: 24.3.0
    spec:
      serviceAccountName: simplapp-sa
      dnsConfig:
        options:
          - name: ndots
            value: "2"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: stack
                    operator: In
                    values:
                      - dev
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - simpleapp
                topologyKey: kubernetes.io/hostname
      containers:
        - name: simpleapp
          image: wayback212/simpleapp:24.3.0
          env:
            - name: PROJECT_VERSION
              value: "24.3.0"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          imagePullPolicy: Always
          resources:
            limits:
              memory: 256Mi
              cpu: 1
            requests:
              memory: 128Mi
              cpu: 1
          readinessProbe:
            httpGet:
              path: /simpleapp/isReady
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 30
          livenessProbe:
            httpGet:
              path: /simpleapp/isAlive
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 30
          ports:
            - containerPort: 8080
              name: smplsrvc

